# Generated by Django 5.0.6 on 2024-07-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('blood', models.CharField(choices=[('A+', 'A+'), ('B+', 'B+'), ('AB+', 'AB+'), ('O+', 'O+')], max_length=3)),
                ('phone', models.CharField(max_length=10)),
                ('phone2', models.CharField(max_length=10, null=True)),
                ('address', models.CharField(max_length=100)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
