# Generated by Django 5.0.6 on 2024-07-07 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locationApp', '0002_country_district_state_delete_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='country_code',
        ),
        migrations.RemoveField(
            model_name='state',
            name='country_code',
        ),
        migrations.AlterField(
            model_name='district',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='locationApp.country'),
        ),
        migrations.AlterField(
            model_name='district',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='locationApp.state'),
        ),
        migrations.AlterField(
            model_name='state',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='locationApp.country'),
        ),
    ]
