# Generated by Django 5.0.6 on 2024-07-07 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locationApp', '0003_remove_district_country_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('contact', models.CharField(max_length=10)),
                ('website', models.URLField(null=True)),
                ('address', models.CharField(max_length=200)),
                ('pin', models.CharField(max_length=6)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='HospitalDetails', to='locationApp.country')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='HospitalDetails', to='locationApp.district')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='HospitalDetails', to='locationApp.state')),
            ],
        ),
    ]
